name: Publish evai

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  regenerate:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create a fresh virtual environment and generate formula
      run: |
        python3 -m venv venv
        source venv/bin/activate
        venv/bin/pip install evai homebrew-pypi-poet
        poet -f evai > Formula/evai.rb
        deactivate
        rm -rf venv
    - name: Replace description and test
      run: |
        python3 -c "
        import re
        content = open('Formula/evai.rb').read()
        content = re.sub(r'desc \"Shiny new formula\"', 'desc \"Access large language models from the command-line\"', content)
        content = content.replace('depends_on \"python3\"', (
            'depends_on \"python3\"\n'
            '  # Needed by pydantic:\\n'
            '  depends_on \"rust\" => :build\\n'
        ))
        content = re.sub(
            r'test do.*?end',
            'test do\\n    assert_match \"evai, version\", shell_output(\"#{bin}/evai --version\")\\n  end',
            content,
            flags=re.DOTALL
        )
        open('Formula/evai.rb', 'w').write(content)
        "
        cat Formula/evai.rb
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Update formula: ${timestamp}" || exit 0
        git pull --rebase
        git push
